

# K8 works with API version to declare the resources
# We have to declare the apiVersion and the kind of service components

apiVersion: apps/v1
kind: Deployment
metadata: 
   name: nginx-deployment # naming the deployment
spec:
   selector:
      matchLabels:
         app: nginx # look for this server to match with K8 service
   # Let's create a replica set of this with 3 instances/pods
   replicas: 2

   # template to use its label for K8 service to launch in browser
   template:
      metadata:
         labels:
            app: nginx # Label to connect service
      
      spec:
            containers:
            - name: nginx
              image: ioanan11/sre_cusomised_nginx:latest
              ports:
              - containerPort: 80
